name: Linux-Clang

on: [push, pull_request, workflow_dispatch]

jobs:
  build-clang-16:
    strategy:
      matrix:
        config: [Debug, Develop, Profile, Release]
      fail-fast: false
        
    runs-on: ubuntu-24.04
    name: Linux x64, Clang 16, ${{matrix.config}}
    timeout-minutes: 90
    
    steps:
    - uses: actions/checkout@v4
       
    - name: Configure dependencies
      run: |
        sudo apt install build-essential pkg-config libx11-dev libxcursor-dev \
          libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libudev-dev \
          libxi-dev libxrandr-dev yasm liburing-dev libpng-dev libbz2-dev libwayland-dev \
          libxkbcommon-dev libc++-dev libc++abi-dev \
          mesa-vulkan-drivers libvulkan1 vulkan-validationlayers
 
    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: |
        mkdir _build
        cd AE-Bin
        wget -O external.zip "https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/d/Q3YGfAA9OoMukg"
        unzip external.zip
    
    - name: Configure CMake
      env:
        CC: clang-16
        CXX: clang++-16
        CPP: clang-cpp-16
        LD: ld.lld-16
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_AVX=1 -DAE_ENABLE_VULKAN=ON -DAE_RES_EDITOR_RELEASE=ON -DAE_GRAPHICS_STRONG_VALIDATION=ON -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
    
    - name: Build
      id: build
      working-directory: ${{github.workspace}}
      run: cmake --build "_build" --config ${{matrix.config}} -j 4

    - name: Release ResEditor
      working-directory: ${{github.workspace}}
      run: |
        mkdir _res_editor
        cp -R "${{github.workspace}}/AE-Temp/samples/res_editor" "_res_editor/ui"
        cp -R "${{github.workspace}}/AE/samples/res_editor/_data" "_res_editor/data"
        cp -R "${{github.workspace}}/AE/engine/shared_data" "_res_editor/shared_data"
        cp "${{github.workspace}}/_build/bin/ResourceEditor" "_res_editor"
        cp "${{github.workspace}}/AE/build_scripts/utils-unix/download-resources.sh" "_res_editor"
      
    - uses: actions/upload-artifact@v4
      with:
        name: AsEn-ResourceEditor-linux-x64-clang16-${{matrix.config}}
        path: ${{github.workspace}}/_res_editor
            
    - uses: actions/upload-artifact@v4
      with:
        name: AsEn-Tools-linux-x64-clang16-${{matrix.config}}
        path: |
            ${{github.workspace}}/_build/bin/CICD
            ${{github.workspace}}/_build/bin/OfflinePacker
            ${{github.workspace}}/_build/bin/RemoteGraphicsDevice
            ${{github.workspace}}/_build/bin/GraphicsRHI-shared.so

    - name: Tests.Base
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Base" -C ${{matrix.config}} -V
      
    - name: Tests.Serializing
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Serializing" -C ${{matrix.config}} -V
        
    - name: Tests.Scripting
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Scripting" -C ${{matrix.config}} -V
        
    - name: Tests.Threading
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Threading" -C ${{matrix.config}} -V
       
    - name: Tests.Networking
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Networking" -C ${{matrix.config}} -V
       
    - name: Tests.ECS
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.ECS-st" -C ${{matrix.config}} -V
       
    - name: Tests.VFS
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.VFS" -C ${{matrix.config}} -V
       
    - name: Tests.AtlasTools
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.AtlasTools" -C ${{matrix.config}} -V
       
    - name: Tests.GeometryTools
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.GeometryTools" -C ${{matrix.config}} -V
       
    - name: Tests.ResourceLoaders
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.ResourceLoaders" -C ${{matrix.config}} -V
        
    - name: Tests.PipelineCompiler
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.PipelineCompiler" -C ${{matrix.config}} -V
            
    - name: Tests.GraphicsRHI
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: |
        cp "${{github.workspace}}/AE-Temp/engine/graphics_rhi/Tests.GraphicsRHI.vkPipelines.bin" "${{github.workspace}}/_build/bin"
        ctest -R "Tests.GraphicsRHI" -C ${{matrix.config}} -V
    
    - name: Tests.Graphics
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: |
        cp "${{github.workspace}}/AE-Temp/engine/graphics/Tests.Graphics.vkPipelines.bin" "${{github.workspace}}/_build/bin"
        ctest -R "^Tests.Graphics$" -C ${{matrix.config}} -V
            
            
  build-clang-16-cxx17:
    strategy:
      matrix:
        config: [Debug]
      fail-fast: false
        
    runs-on: ubuntu-24.04
    name: Linux x64, Clang 16, C++17, ${{matrix.config}}
    timeout-minutes: 90
    
    steps:
    - uses: actions/checkout@v4
       
    - name: Configure dependencies
      run: |
        sudo apt install build-essential pkg-config libx11-dev libxcursor-dev \
          libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libudev-dev \
          libxi-dev libxrandr-dev yasm liburing-dev libpng-dev libbz2-dev libwayland-dev \
          libxkbcommon-dev libc++-dev libc++abi-dev
 
    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: |
        mkdir _build
        cd AE-Bin
        wget -O external.zip "https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/d/Q3YGfAA9OoMukg"
        unzip external.zip
    
    - name: Configure CMake
      env:
        CC: clang-16
        CXX: clang++-16
        CPP: clang-cpp-16
        LD: ld.lld-16
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_ENABLE_VULKAN=ON -DAE_RES_EDITOR_RELEASE=ON -DAE_GRAPHICS_STRONG_VALIDATION=ON -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -DAE_FORCE_CXX17=ON -S "AE" -B "_build"
    
    - name: Build
      id: build
      working-directory: ${{github.workspace}}
      run: cmake --build "_build" --config ${{matrix.config}} -j 4
 
    - name: Tests.Base
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Base" -C ${{matrix.config}} -V
      
    - name: Tests.Serializing
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Serializing" -C ${{matrix.config}} -V
        
    - name: Tests.Scripting
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Scripting" -C ${{matrix.config}} -V
        
    - name: Tests.Threading
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Threading" -C ${{matrix.config}} -V
       
    - name: Tests.Networking
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Networking" -C ${{matrix.config}} -V
       
    - name: Tests.ECS
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.ECS-st" -C ${{matrix.config}} -V
       
    - name: Tests.VFS
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.VFS" -C ${{matrix.config}} -V
      
      
      
  build-clang-16-cxx20:
    strategy:
      matrix:
        config: [Debug]
      fail-fast: false
        
    runs-on: ubuntu-24.04
    name: Linux x64, Clang 16, C++20, ${{matrix.config}}
    timeout-minutes: 90
    
    steps:
    - uses: actions/checkout@v4
       
    - name: Configure dependencies
      run: |
        sudo apt install build-essential pkg-config libx11-dev libxcursor-dev \
          libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libudev-dev \
          libxi-dev libxrandr-dev yasm liburing-dev libpng-dev libbz2-dev libwayland-dev \
          libxkbcommon-dev libc++-dev libc++abi-dev
 
    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: |
        mkdir _build
        cd AE-Bin
        wget -O external.zip "https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/d/Q3YGfAA9OoMukg"
        unzip external.zip
    
    - name: Configure CMake
      env:
        CC: clang-16
        CXX: clang++-16
        CPP: clang-cpp-16
        LD: ld.lld-16
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_ENABLE_VULKAN=ON -DAE_RES_EDITOR_RELEASE=ON -DAE_GRAPHICS_STRONG_VALIDATION=ON -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -DAE_FORCE_CXX20=ON -S "AE" -B "_build"
    
    - name: Build
      id: build
      working-directory: ${{github.workspace}}
      run: cmake --build "_build" --config ${{matrix.config}} -j 4
 
    - name: Tests.Base
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Base" -C ${{matrix.config}} -V
      
    - name: Tests.Serializing
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Serializing" -C ${{matrix.config}} -V
        
    - name: Tests.Scripting
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Scripting" -C ${{matrix.config}} -V
        
    - name: Tests.Threading
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Threading" -C ${{matrix.config}} -V
       
    - name: Tests.Networking
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.Networking" -C ${{matrix.config}} -V
       
    - name: Tests.ECS
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.ECS-st" -C ${{matrix.config}} -V
       
    - name: Tests.VFS
      working-directory: ${{github.workspace}}/_build
      if: success() || steps.build.conclusion == 'success'
      run: ctest -R "Tests.VFS" -C ${{matrix.config}} -V
      
    
    
  build-clang-16-rg:
    strategy:
      matrix:
        config: [Debug, Profile]
      fail-fast: false
        
    runs-on: ubuntu-24.04
    name: Linux x64, Clang 16, ${{matrix.config}}, RemoteGraphics
    timeout-minutes: 90
    
    steps:
    - uses: actions/checkout@v4
       
    - name: Configure dependencies
      run: |
        sudo apt install build-essential pkg-config libx11-dev libxcursor-dev \
          libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libudev-dev \
          libxi-dev libxrandr-dev yasm liburing-dev libpng-dev libbz2-dev libwayland-dev \
          libxkbcommon-dev libc++-dev libc++abi-dev
 
    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: |
        mkdir _build
        cd AE-Bin
        wget -O external.zip "https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/d/Q3YGfAA9OoMukg"
        unzip external.zip
    
    - name: Configure CMake
      env:
        CC: clang-16
        CXX: clang++-16
        CPP: clang-cpp-16
        LD: ld.lld-16
      shell: bash
      working-directory: ${{github.workspace}}
      run: cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_ENABLE_REMOTE_GRAPHICS=ON -DAE_RES_EDITOR_RELEASE=ON -DAE_GRAPHICS_STRONG_VALIDATION=ON -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
    
    - name: Build
      id: build
      working-directory: ${{github.workspace}}
      run: cmake --build "_build" --config ${{matrix.config}} -j 4 --target "ResourceEditor"
      
    - name: Release ResEditor
      working-directory: ${{github.workspace}}
      run: |
        mkdir _res_editor
        cp -R "${{github.workspace}}/AE-Temp/samples/res_editor" "_res_editor/ui"
        cp -R "${{github.workspace}}/AE/samples/res_editor/_data" "_res_editor/data"
        cp -R "${{github.workspace}}/AE/engine/shared_data" "_res_editor/shared_data"
        cp "${{github.workspace}}/_build/bin/ResourceEditor" "_res_editor"
        cp "${{github.workspace}}/AE/build_scripts/utils-unix/download-resources.sh" "_res_editor"
      
    - uses: actions/upload-artifact@v4
      with:
        name: AsEn-ResourceEditor-linux-x64-clang16-${{matrix.config}}-RemoteGraphics
        path: ${{github.workspace}}/_res_editor
            
            
