name: MacOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        config: [Debug, Develop, Profile, Release]
    
    runs-on: macos-latest
    name: MacOS ARM64, ${{matrix.config}}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: |
        mkdir _build
        cd AE-Bin
        wget -O external.zip "https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/d/i4Q642wgttN8Gw"
        unzip external.zip
      
    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.config}} -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_OSX_ARCHITECTURES=arm64 -DAE_ENABLE_VULKAN=ON -DAE_USE_PCH=OFF -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
    
    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build "_build" --config ${{matrix.config}} -j 2

    - name: Test
      working-directory: ${{github.workspace}}/_build
      run: |
        ctest -R "Tests.Base" -C ${{matrix.config}}
        ctest -R "Tests.Serializing" -C ${{matrix.config}}
        ctest -R "Tests.ResourceLoaders" -C ${{matrix.config}}
        ctest -R "Tests.Threading" -C ${{matrix.config}}
        ctest -R "Tests.Networking" -C ${{matrix.config}}
        ctest -R "Tests.ECS-st" -C ${{matrix.config}}
        ctest -R "Tests.VFS" -C ${{matrix.config}}
        ctest -R "Tests.AtlasTools" -C ${{matrix.config}}
        ctest -R "Tests.GeometryTools" -C ${{matrix.config}}

    - uses: actions/upload-artifact@v4
      with:
        name: AsEn-macos-arm64-${{matrix.config}}
        path: |
            ${{github.workspace}}/_build/bin/CICD.app
            ${{github.workspace}}/_build/bin/RemoteGraphicsDevice.app
            
            