name: MacOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        config: [Debug, Develop, Profile, Release]
    
    runs-on: macos-latest
    name: MacOS ARM64, ${{matrix.config}}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: |
        mkdir _build
        cd AE-Bin
        wget -O external.zip "https://getfile.dokpub.com/yandex/get/https://disk.yandex.ru/d/eP2spVG3SkgDcQ"
        unzip external.zip
      
    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -DCMAKE_BUILD_TYPE=${{matrix.config}} -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 -DCMAKE_OSX_ARCHITECTURES=arm64 -DAE_ENABLE_VULKAN=ON -DAE_USE_PCH=OFF -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
    
    - name: Build
      working-directory: ${{github.workspace}}
      run: cmake --build "_build" --config ${{matrix.config}} -j 2

    - uses: actions/upload-artifact@v4
      with:
        name: AsEn-ResourceEditor-macos-arm64-${{matrix.config}}
        path: |
            ${{github.workspace}}/_build/bin/ResourceEditor.app
            
    - uses: actions/upload-artifact@v4
      with:
        name: AsEn-Tools-macos-arm64-${{matrix.config}}
        path: |
            ${{github.workspace}}/_build/bin/CICD.app
            ${{github.workspace}}/_build/bin/GraphicsLib.so
            ${{github.workspace}}/_build/bin/OfflinePacker.app
            ${{github.workspace}}/_build/bin/RemoteGraphicsDevice.app

    - name: Tests.Base
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.Base" -C ${{matrix.config}} -V
      
    - name: Tests.Serializing
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.Serializing" -C ${{matrix.config}} -V
        
    - name: Tests.Scripting
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.Scripting" -C ${{matrix.config}} -V
        
    - name: Tests.Threading
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.Threading" -C ${{matrix.config}} -V
       
    - name: Tests.Networking
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.Networking" -C ${{matrix.config}} -V
       
    - name: Tests.ECS
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.ECS-st" -C ${{matrix.config}} -V
       
    - name: Tests.VFS
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.VFS" -C ${{matrix.config}} -V
       
    - name: Tests.AtlasTools
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.AtlasTools" -C ${{matrix.config}} -V
       
    - name: Tests.GeometryTools
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.GeometryTools" -C ${{matrix.config}} -V
       
    - name: Tests.ResourceLoaders
      working-directory: ${{github.workspace}}/_build
      run: ctest -R "Tests.ResourceLoaders" -C ${{matrix.config}} -V
     
            