name: Linux-SSE

on: [push, pull_request, workflow_dispatch]

jobs:
  build-clang-18:
    strategy:
      matrix:
        config: [Debug]
      fail-fast: false
        
    runs-on: ubuntu-24.04
    name: Linux x64, Clang 18, SSE/AVX, ${{matrix.config}}
    
    steps:
    - uses: actions/checkout@v4
       
    - name: Configure dependencies
      run: |
        sudo apt install build-essential pkg-config libx11-dev libxcursor-dev \
          libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev \
          libxi-dev libxrandr-dev yasm liburing-dev libpng-dev libbz2-dev libwayland-dev \
          libxkbcommon-dev libc++-dev libc++abi-dev
 
    - name: Create Build Environment
      working-directory: ${{github.workspace}}
      run: |
        mkdir _build
        cd AE-Bin
        chmox +x download-linux-x64-clang.sh
        ./download-linux-x64-clang.sh
        mv external/linux-x64-clang20 external/linux-x64-clang18
    
    - name: AVX512 (Zen4)
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_AVX=33 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
      
    - name: AVX512 (Ice Lake)
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_AVX=32 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
      
    - name: AVX512 (Cannon Lake)
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_AVX=31 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
      
    - name: AVX512 (basic)
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_AVX=30 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
      
    - name: AVX2
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_AVX=2 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
      
    - name: AVX1
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_AVX=1 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
      
    - name: SSE 4.2
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_SSE=42 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
      
    - name: SSE 4.1
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_SSE=41 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
      
    - name: SSSE 3
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_SSE=31 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
        
    - name: SSE 3
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_SSE=30 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
        
    - name: SSE 2.0
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_SSE=20 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
        
    - name: SSE 2.0 & SHA2
      env:
        CC: clang-18
        CXX: clang++-18
        CPP: clang-cpp-18
        LD: ld.lld-18
      shell: bash
      working-directory: ${{github.workspace}}
      if: success() || failure()
      run: |
        rm -rf "_build"
        cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=${{matrix.config}} -DAE_SIMD_SSE=20 -DAE_SIMD_SHA=20 -DAE_CI_BUILD_TEST=ON -DAE_ENABLE_LOGS=ON -S "AE" -B "_build"
        cmake --build "_build" --config ${{matrix.config}} -j 4 --target Tests.Base
        
